spring:
  application:
    name: order
  datasource:
    druid:
      url: jdbc:mysql://47.106.109.20:3306/trade?useSSL=false
      username: root
      password: Iftk@414228
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 50
      max-active: 50
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
  rabbitmq:
    host: 192.168.0.200
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    hostname: 192.168.0.200
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:2001/eureka
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    #  使用jdbc的自增主键
    use-generated-keys: true
    #  使用列表名来代替列名
    use-column-label: true
    #  开启驼峰转换
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-prefix: mybatis-sql-log
    # 避免查询结果类型为map的时候，如果控制在map中不会出现这个属性
    call-setters-on-nulls: true
server:
  port: 3011


